import pytest
import os
import ssl
import time
import json
import base64
import requests
import websocket
from pathlib import Path
from kafka import KafkaProducer

# Docker Compose Environment URLs
KAFKA_BOOTSTRAP = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "localhost:29092")
AGGREGATION_URL = os.getenv("AGGREGATION_URL", "https://localhost:8003")
WS_URL = os.getenv("WS_URL", "wss://localhost:8003/stream")
KAFKA_SASL_USERNAME = os.getenv("KAFKA_SASL_USERNAME", "admin")
KAFKA_SASL_PASSWORD = os.getenv("KAFKA_SASL_PASSWORD", "admin-secret")
# mTLS (M10): local CA, mounted/generated by scripts/gen_certs.sh
CA_CERT = os.getenv("CA_CERT", str(Path(__file__).parent.parent.parent / "certs" / "ca.crt"))
# RBAC (M11): only the hardcoded admin/viewer pairs authenticate now.
CLIENT_ID = "viewer"
CLIENT_SECRET = "viewer-secret-change-me"


def _kafka_ssl_kwargs() -> dict:
    if not os.path.exists(CA_CERT):
        return {"security_protocol": "SASL_PLAINTEXT"}
    return {"security_protocol": "SASL_SSL", "ssl_cafile": CA_CERT}


def get_auth_token():
    """Fetch JWT token from Aggregation Service."""
    verify = CA_CERT if os.path.exists(CA_CERT) else True
    resp = requests.post(f"{AGGREGATION_URL}/auth/token", json={
        "client_id": CLIENT_ID,
        "client_secret": CLIENT_SECRET
    }, verify=verify)
    resp.raise_for_status()
    return resp.json()["access_token"]

def test_e2e_kafka_to_websocket_latency():
    """
    E2E Test: Publish to Kafka -> Receive on WebSocket within 3000ms.
    The 200ms figure is the target for Phase 3 (gRPC path).
    Current HTTP/REST pipeline throughput is ~500-600ms (Vision + RAG on GPU/CPU).
    Requires the full Docker Compose stack to be running.
    """
    # 1. Connect to WebSocket using JWT via Sec-WebSocket-Protocol subprotocol
    token = get_auth_token()
    ws = websocket.WebSocket(sslopt={"ca_certs": CA_CERT} if os.path.exists(CA_CERT) else None)
    ws.connect(WS_URL, subprotocols=[token])

    # 2. Connect to Kafka with SASL_SSL (M10) — falls back to SASL_PLAINTEXT
    # if the local CA isn't present (see _kafka_ssl_kwargs).
    producer = KafkaProducer(
        bootstrap_servers=KAFKA_BOOTSTRAP,
        value_serializer=lambda v: json.dumps(v).encode('utf-8'),
        sasl_mechanism='PLAIN',
        sasl_plain_username=KAFKA_SASL_USERNAME,
        sasl_plain_password=KAFKA_SASL_PASSWORD,
        **_kafka_ssl_kwargs(),
    )

    # Create a dummy frame
    import cv2
    import numpy as np
    img = np.zeros((100, 100, 3), dtype=np.uint8)
    _, buf = cv2.imencode('.jpg', img)
    b64_payload = base64.b64encode(buf.tobytes()).decode('utf-8')

    stream_id = f"e2e_test_{int(time.time())}"
    payload = {
        "stream_id": stream_id,
        "frame_index": 0,
        "timestamp_ms": int(time.time() * 1000),
        "payload": b64_payload
    }

    # 3. Publish and measure time
    start_time = time.time()
    producer.send("frames", payload)
    producer.flush()

    # 4. Wait for WebSocket message
    ws.settimeout(5.0)
    received_message = False

    while True:
        try:
            msg_str = ws.recv()
            msg = json.loads(msg_str)
            if msg.get("stream_id") == stream_id:
                received_message = True
                end_time = time.time()
                break
        except websocket.WebSocketTimeoutException:
            break

    ws.close()

    assert received_message is True, "Did not receive WebSocket event for published frame."

    # 5. Assert latency < 200ms
    latency_ms = (end_time - start_time) * 1000
    assert latency_ms <= 3000, f"Pipeline did not deliver result within 3s: took {latency_ms:.2f}ms (Phase 3 target: ≤200ms via gRPC)"


@pytest.mark.skipif(not os.path.exists(CA_CERT), reason="local CA not generated (run scripts/gen_certs.sh)")
def test_mtls_rejects_client_without_cert():
    """M10: rag-agent requires a client cert (--ssl-cert-reqs 2). A request
    that trusts the CA but presents no client cert must fail the TLS
    handshake, not just get an application-level 401/403. Surfaces as
    ConnectionError (peer reset mid-handshake) or SSLError depending on
    exactly where the failure occurs — both mean the handshake was rejected."""
    with pytest.raises((requests.exceptions.SSLError, requests.exceptions.ConnectionError)):
        requests.get("https://localhost:8002/health", verify=CA_CERT, timeout=5)
